apiVersion: v1
kind: Service
metadata:
  name: web-bff-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: WebBff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bff-deployment
spec:
  selector:
    matchLabels:
      app: WebBff
  replicas: 2
  template:
    metadata:
      labels:
        app: WebBff
    spec:
      containers:
        - name: web-bff
          image: 719042170775.dkr.ecr.us-west-2.amazonaws.com/jbaumgartner/web-bff:latest
          ports:
            - containerPort: 8080
